<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('jobs')->insert([
            [
                'user_id' => 2,
                'category_id' => 1,
                'title' => "Membuat Illustration Design",
                'slug' => "membuat-illustration-design",
                'description' => "As an illustrator I'm mainly focusing on character and nature/ landscape illustrations. Depending on the package you're choosing, I'll create a coloured, digital illustration of your favorite landscape/character. For my illustrations I use procreate, so you'll get a High Resolution File as well as the open source file (I can export a photoshop file).",
                'job_style' => "Minimalist / Playful",
                'file_format' => "AI, JPG, PNG, SVG, PSD, EPS",
                'package_name' => "Paket Hemat",
                'package_description' => "TEXT logo only in esports style - JPG & PNG transparent",
                'job_delivery' => 5,
                'revision' => 4,
                'price' => 350000,
            ],
            [
                'user_id' => 4,
                'category_id' => 2,
                'title' => "Build Website and Design",
                'slug' => "build-website-and-design",
                'description' => "Hi , I am Website Designer. I have designing experience Wix Wordpres Shopify CMS over 2 years and it is very great for new startups and businesses. I will provide exceptional quality quick service and response to your queries on first priority. I'll make websites on all CMS platforms like Godaddy, Square Space, BigCommerce etc. The mobile optimization (View) so your web.site looks equally good across all devices.",
                'job_style' => "Website",
                'file_format' => "HTML, JPG",
                'package_name' => "Website Builder",
                'package_description' => "Unlimited Panels/Buttons + Offline screen",
                'job_delivery' => 7,
                'revision' => 3,
                'price' => 1800000,
            ],
            [
                'user_id' => 3,
                'category_id' => 8,
                'title' => "Create Exercise Video",
                'slug' => "create-exercice-video",
                'description' => "What sets me apart from the other sellers on here is my doctoral-level knowledge of the human body and exercise. Have exercises and movements explained accurately and correctly by a professional in your video to show your company is credible.",
                'job_style' => "Strength Training",
                'file_format' => "MP4",
                'package_name' => "Paket Murah",
                'package_description' => "1 Emote Vector or Chibi Style Three PNG file (112px, 56px and 28px)",
                'job_delivery' => 2,
                'revision' => 4,
                'price' => 130000,
            ],
            [
                'user_id' => 5,
                'category_id' => 5,
                'title' => "Editing Clips Video",
                'slug' => "editing-clips-video",
                'description' => "Are you looking for a Video Editor to edit your clips and turn it into an amazing montage well you've come to the right place,",
                'job_style' => "Gaming Videos",
                'file_format' => "MP4",
                'package_name' => "EZ Montage",
                'package_description' => "UNLIMITED PANELS AND FACECAM(basic)",
                'job_delivery' => 3,
                'revision' => 3,
                'price' => 100000,
            ],
            [
                'user_id' => 7,
                'category_id' => 4,
                'title' => "SEO Blog Post",
                'slug' => "seo-blog-post",
                'description' => "Welcome to my SEO article writing gig! I'm so glad you're here! This is my top selling service here on Fiverr. I offer article writing in a wide variety of fields ranging from health/wellness to art to technology to pet care! Feel free to message me to discuss your topic niche prior to the purchase of a gig!",
                'job_style' => "First Person Narrative",
                'file_format' => "docx, PDF",
                'package_name' => "SEO Post",
                'package_description' => "1 custom badge or emote in 3 size",
                'job_delivery' => 1,
                'revision' => 5,
                'price' => 300000,
            ],
            [
                'user_id' => 6,
                'category_id' => 7,
                'title' => "Train Crypto Trading",
                'slug' => "train-crypto-trading",
                'description' => "99% of trading gurus you find online are retail traders. They trade cryptocurrency using candlesticks, resistances & supports, trend lines, and indicators. The dilemma is that what they show in their lessons are cherry-picked areas of charts. Their crypto trading strategies work sometimes, but the majority of times they fail.",
                'job_style' => "Online Session",
                'file_format' => "-",
                'package_name' => "Trading Lessons",
                'package_description' => "Unlimited Panels +Facecam+offline screen",
                'job_delivery' => 7,
                'revision' => 2,
                'price' => 5600000,
            ],
            [
                'user_id' => 3,
                'category_id' => 3,
                'title' => "Create Facebook Marketing",
                'slug' => "create-facebook-marketing",
                'description' => "Hello Dear Sir/Madame, Are you looking for someone to Promote your business. I am Social Media Marketing Expert. I have taken a long time training in Facebook Marketing work. I have a lot of experience with Facebook marketing job. I can do write the description of any product makes Interesting. I know all the rules of Facebook marketing work and do the work manually. So I think, I can any business Facebook marketing job very well.",
                'job_style' => "Marketing",
                'file_format' => "PDF, JPG",
                'package_name' => "Basic Package",
                'package_description' => "1 EMOTES (28px,56px,112px,1000px) or 1 SUB BADGES (18px,36px,71px,1000px), PNG format",
                'job_delivery' => 3,
                'revision' => 4,
                'price' => 740000,
            ],
            [
                'user_id' => 2,
                'category_id' => 9,
                'title' => "Design NFT Art",
                'slug' => "design-nft-art",
                'description' => "You know that NFT is hot right now. You'd like to cash in on the opportunity. But you need a talented NFT artist to make your vision come true.",
                'job_style' => "2D",
                'file_format' => "JPG, PNG, SVG, PSD, AI",
                'package_name' => "Creative Package",
                'package_description' => "Creative Package Description",
                'job_delivery' => 4,
                'revision' => 7,
                'price' => 1200000,
            ],
            [
                'user_id' => 4,
                'category_id' => 1,
                'title' => "Design Modern Minimalist Logo",
                'slug' => "design-modern-minimalist-logo",
                'description' => "We Perfectionist is a highly talented and dedicated team, focused on providing unique logo design absolutely from scratch. A Logo is the face of your brand which is as equally important as the success of your business and we make sure to dig the pillars of your success from depth.",
                'job_style' => "Modern, Minimalist",
                'file_format' => "JPG, PNG, SVG, PSD, AI, EPS",
                'package_name' => "Standard",
                'package_description' => "Standard Description",
                'job_delivery' => 3,
                'revision' => 2,
                'price' => 310000,
            ],
            [
                'user_id' => 6,
                'category_id' => 5,
                'title' => "Create Animated GIF",
                'slug' => "create-animated-gif",
                'description' => "I will create custom perfect looped animated Gif, logo animation, Social Media Gif, Landing page Gif, Product Gif, Giphy stickers, Intagram Gif, with file format Gif/MP4.",
                'job_style' => "Animation",
                'file_format' => "GIF, PNG, MP4",
                'package_name' => "Premium Package",
                'package_description' => "Premium Package Description",
                'job_delivery' => 2,
                'revision' => 6,
                'price' => 630000,
            ],
            [
                'user_id' => 3,
                'category_id' => 2,
                'title' => "Develope Mobile Apps and Website",
                'slug' => "develope-mobile-apps-and-website",
                'description' => " We're a team of Strategists, Designers, and Developers, We have an insatiable thirst for helping clients build beautiful and modern products for real people. Our mission is to help companies solve problems with design and technology.",
                'job_style' => "Android Apps",
                'file_format' => "Application",
                'package_name' => "Gold Package",
                'package_description' => "Gold Package Description",
                'job_delivery' => 45,
                'revision' => 3,
                'price' => 12500000,
            ],
            [
                'user_id' => 5,
                'category_id' => 6,
                'title' => "Record American Male Voice Over",
                'slug' => "record-american-male-voice-over",
                'description' => "I trained at Edge Studio in New York City, and I have 10+ years of pro experience giving clients exactly the sound they need. Just tell me the style, you want, and I'll record your script for:",
                'job_style' => "English",
                'file_format' => "MP3, Audio",
                'package_name' => "Standard Audio",
                'package_description' => "Standard Audio description",
                'job_delivery' => 5,
                'revision' => 3,
                'price' => 450000,
            ],
            [
                'user_id' => 2,
                'category_id' => 1,
                'title' => "Design Esport Logo",
                'slug' => "design-esport-logo",
                'description' => "Thankyou for visiting my gig! Did you looking for esports logo? well search no further because in this gig i will professionaly create esports logo. I am very experienced in making Mascot logo, This suitable for your YouTube, twitch, community, esport team, etc.",
                'job_style' => "Esport Logo",
                'file_format' => "JPG, PNG, SVG, AI, PSD, EPS",
                'package_name' => "Basic Package",
                'package_description' => "Basic Package description",
                'job_delivery' => 3,
                'revision' => 1,
                'price' => 80000,
            ],
        ]);
    }
}
