<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('users')->insert([
            [
                'first_name' => 'Admin',
                'last_name' => '',
                'full_name' => 'Admin',
                'username' => 'admin',
                'email' => 'admin@projectin.com',
                'phone_number' => '081213980912',
                'university' => 'Bina Nusantara University',
                'region' => 'Indonesia',
                'region_id' => 'id',
                'role' => 'Admin',
                'quote' => 'The best admin in the world',
                'description' => 'This is Admin of Projectin',
                'is_admin' => true,
                'is_freelancer' => false,
                'is_buyer' => false,
                'is_verified' => true,
                'password' => bcrypt('admin'),
            ],
            [
                'first_name' => 'Jake',
                'last_name' => 'Woko',
                'full_name' => 'Jake Woko',
                'username' => 'jakewoko',
                'email' => 'jake.woko@gmail.com',
                'phone_number' => '081371826310',
                'university' => 'Bina Nusantara University',
                'region' => 'Indonesia',
                'region_id' => 'id',
                'role' => 'Logo Designer',
                'quote' => 'I love design since I was at high school',
                'description' => 'Hello and welcome. I am a Web designer, WordPress developer, and Godaddy website designer. I have more than 5+ years of experience in designing and developing elegant websites.',
                'is_admin' => false,
                'is_freelancer' => true,
                'is_buyer' => true,
                'is_verified' => false,
                'password' => bcrypt('password123'),
            ],
            [
                'first_name' => 'Paulina',
                'last_name' => 'Lena Kosasih',
                'full_name' => 'Paulina Lena Kosasih',
                'username' => 'paulinalena',
                'email' => 'paulina.lena@gmail.com',
                'phone_number' => '081234109231',
                'university' => 'UPH University',
                'region' => 'Indonesia',
                'region_id' => 'id',
                'role' => 'Programmer',
                'quote' => "Programming is my life. I love to code, because I'am a geek",
                'description' => "Hi there, I’m Tascha, a Berlin based illustrator :) For more information check out my Instagram: Trudeiskrude I can’t wait to start working with you!",
                'is_admin' => false,
                'is_freelancer' => true,
                'is_buyer' => true,
                'is_verified' => false,
                'password' => bcrypt('password123'),
            ],
            [
                'first_name' => 'Amalia',
                'last_name' => 'Santoso Djaja',
                'full_name' => 'Amalia Santoso Djaja',
                'username' => 'amaliasantoso',
                'email' => 'amalia.santoso@gmail.com',
                'phone_number' => '081349872699',
                'university' => 'Mercu Buana University',
                'region' => 'Indonesia',
                'region_id' => 'id',
                'role' => 'Video Editor',
                'quote' => 'This is my passion, my life, and my adventure.',
                'description' => "Hi, my name is Nebojsa and I am a passionate trumpet player (20+ years) and teacher, Van Laar artist and lead in a band with experience in the music industry of 15 years. I have toured the world with my band S.A.R.S. (reggae, rock, pop, ska, hip hop, r'n'b, Balkan folk) and also play in Belgrade based band Freaky Fight for Freedom (rock, grunge, d&b and hard rock.) Please reach out to me with any questions you have, I'm here to make sure you get exactly what you are looking for. look forward to working with you!",
                'is_admin' => false,
                'is_freelancer' => true,
                'is_buyer' => true,
                'is_verified' => false,
                'password' => bcrypt('password123'),
            ],
            [
                'first_name' => 'Budi',
                'last_name' => 'Setiawan Handoko',
                'full_name' => 'Budi Setiawan Handoko',
                'username' => 'budisetiawan',
                'email' => 'budi.setiawan@gmail.com',
                'phone_number' => '08127390291',
                'university' => 'UNTAR University',
                'region' => 'Indonesia',
                'region_id' => 'id',
                'role' => 'Illustrator',
                'quote' => 'I will design an illustrator for you, I love it',
                'description' => "I have been a professional gamer in multiple titles starting my senior year of high school. I've played in many tournaments across different countries and I put my all into every game that I play. I'm interested in helping more people up their game and be the best player they can be.",
                'is_admin' => false,
                'is_freelancer' => true,
                'is_buyer' => true,
                'is_verified' => false,
                'password' => bcrypt('password123'),
            ],
            [
                'first_name' => 'Carl',
                'last_name' => 'Joshua',
                'full_name' => 'Carl Joshua',
                'username' => 'carljoshua',
                'email' => 'carl.joshua@gmail.com',
                'phone_number' => '081315567255',
                'university' => 'President University',
                'region' => 'Indonesia',
                'region_id' => 'id',
                'role' => 'Trainer',
                'quote' => 'I love to exercise myself everyday, I love to make a video too.',
                'description' => "I have managed all aspects of PR for private clients ranging from small business owners to public CEO figures. I'm thrilled to assist with any of your editorial and written needs, whether it's creating blog posts and articles or profiles and e-books, I am determined to help you achieve your goals.",
                'is_admin' => false,
                'is_freelancer' => true,
                'is_buyer' => true,
                'is_verified' => false,
                'password' => bcrypt('password123'),
            ],
            [
                'first_name' => 'Livy',
                'last_name' => 'Renata',
                'full_name' => 'Livy Renata',
                'username' => 'livyrenata',
                'email' => 'livy.renata@gmail.com',
                'phone_number' => '081372889911',
                'university' => 'Institut Teknologi Bandung',
                'region' => 'Indonesia',
                'region_id' => 'id',
                'role' => 'Finance Consultant',
                'quote' => 'Money is everything for me, money makes me happy.',
                'description' => "We are Bucharest Team. Professionals in the design industry with over 7 years of work experience. Well versed in using tools to produce solutions that have a meaningful impact on your business. Our knowledge, vision, and management were tested and proven in various projects.",
                'is_admin' => false,
                'is_freelancer' => true,
                'is_buyer' => true,
                'is_verified' => false,
                'password' => bcrypt('password123'),
            ],
        ]);
    }
}
